### ISSUE TITLE
scheduled jobs internal error

### ISSUE THREAD

**Issue by giorgiorossi** [OrderOfTheBee/ootbee-support-tools#128]
## BUG
Unable to access scheduled jobs from ootb tools

### Actual behavior
The Web Script /alfresco/s/ootbee/admin/scheduled-jobs has responded with a status of 500 - Internal Error.

500 Description:	An error inside the HTTP server which prevented it from fulfilling the request.
 
Message:	08240015 Wrapped Exception (with status template): 08240049 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js': Invalid expression: 0/20/40
Server:	Community v5.2.0 (re21f2be5-b22) schema 10.057
Time:	24-set-2018 12.56.49

### Steps to reproduce the behavior
click on scheduled jobs in ootb tools

### Additional details (analysis so far, log statements, references, etc.)
LOG:

2018-09-24 12:35:37,957  INFO  [solr.component.AsyncBuildSuggestComponent] [Suggestor-alfresco-1] Built suggester shingleBasedSuggestions, took 6450 ms
 2018-09-24 12:35:47,326  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-12] Exception from executeScript: 08240013 Wrapped Exception (with status templ
ate): 08240038 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js': Invali
d expression: 0/20/40
 org.springframework.extensions.webscripts.WebScriptException: 08240013 Wrapped Exception (with status template): 08240038 Failed to execute script 'classpath*:alfresco/te
mplates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js': Invalid expression: 0/20/40
        at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1138)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:467)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
        at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2486)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.alfresco.scripts.ScriptException: 08240038 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-s
upport-tools/scheduled-jobs.get.js': Invalid expression: 0/20/40
        at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:211)
        at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
        at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
        at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
        at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
        ... 34 more
Caused by: java.lang.IllegalArgumentException: Invalid expression: 0/20/40
        at com.cronutils.parser.FieldParser.slashSplit(FieldParser.java:99)
        at com.cronutils.parser.FieldParser.dashSplitResult(FieldParser.java:79)
        at com.cronutils.parser.FieldParser.parse(FieldParser.java:70)
        at com.cronutils.parser.CronParserField.parse(CronParserField.java:60)
        at com.cronutils.parser.CronParser.parse(CronParser.java:90)
        at sun.reflect.GeneratedMethodAccessor841.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
        at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18._c_build
ScheduledJobsData_9(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js:283)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18.call(cla
sspath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js)
        at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18._c_scrip
t_0(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js:430)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18.call(cla
sspath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18.call(cla
sspath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js)
        at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18.exec(cla
sspath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js)
        at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
        at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
        ... 39 more

### Tell us about your environment
CentOS Linux release 7.2.1511 (Core)
Alfresco Community (Build: 201707)

Thanks in advance

**Comment by AFaust** [comment]
It looks like you have a custom configured CRON expression for a job that our util for parsing into a human-readable display text considers invalid. Can you please provide the full CRON expression so we can reproduce / check this?

**Comment by AFaust** [comment]
Generally we do support CRON expressions like 0/5 for intervals of 5 starting at 0, but I have never seen a valid CRON expression with more than one forward slash. Are you sure you did not mean to configure 0,20,40 instead of 0/20/40?

**Comment by AFaust** [comment]
Nonetheless - we should not fail hard if a human-readable text (a "nice-to-have" cannot be generated).

**Comment by giorgiorossi** [comment]
There was a mistake in a cron expression in a custom webscript.

Thanks for Your help,
