### ISSUE TITLE
Using JAR Deployment produces errors in some options for Alfresco Admin Web Console

### ISSUE THREAD

**Issue by aborroy** [OrderOfTheBee/ootbee-support-tools#145]
## BUG

Some options are not available when deploying `support-tools-repo-1.1.0.0.jar` instead of AMP release. Tested that these options work when using AMP.

### Expected behavior

*System Information* and *Scheduled Jobs* options are available from Alfresco Admin Web Console.

### Actual behavior

When clicking on "System Information", following exception appears and the option is not available:

```
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call property of in object [JavaPackage net.time4j.Duration]. It is not a function, it is "object". (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.js#233)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4198)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4176)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4209)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.typeError3(ScriptRuntime.java:4235)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4303)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2575)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2557)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_system_information_get_js_14._c_buildSystemInformation_8(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.js:233)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_system_information_get_js_14.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.js)
alfresco_1     | 	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_system_information_get_js_14._c_script_0(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.js:261)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_system_information_get_js_14.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.js)
alfresco_1     | 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_system_information_get_js_14.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.js)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_system_information_get_js_14.exec(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/system-information.get.js)
alfresco_1     | 	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
alfresco_1     | 	... 113 more
```

When clicking on "Scheduled Jobs", following exception appears and the option is not available:

```
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot call property instanceDefinitionFor in object [JavaPackage com.cronutils.model.definition.CronDefinitionBuilder]. It is not a function, it is "object". (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js#248)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4198)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4176)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:4209)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.typeError3(ScriptRuntime.java:4235)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4303)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2575)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2557)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18._c_buildScheduledJobsData_9(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js:248)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js)
alfresco_1     | 	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18._c_script_0(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js:430)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js)
alfresco_1     | 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
alfresco_1     | 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js)
alfresco_1     | 	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_support_tools_admin_ootbee_support_tools_scheduled_jobs_get_js_18.exec(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/scheduled-jobs.get.js)
alfresco_1     | 	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
alfresco_1     | 	... 111 more
```

### Steps to reproduce the behavior

Deploy JAR artifact to Alfresco 6.1 using Docker Compose template.

### Additional details (analysis so far, log statements, references, etc.)

Using Docker Compose template based in https://github.com/Alfresco/alfresco-docker-installer and selecting ACS 6.1

**Comment by aborroy** [comment]
When deploying as JAR, following dependencies are required also to be added:

https://github.com/OrderOfTheBee/ootbee-support-tools/blob/master/repository/pom.xml#L76

* com.cronutils.cron-utils:5.0.3

* net.time4j.time4j-core:3.23

* net.time4j.time4j-i18n:3.23

This libraries must be copied to JAR deployment folder in Alfresco.

**Comment by yregaieg** [comment]
@AFaust Shall we produce a fat jar with the needed packages pre-bundled or shall we simply document the required dependencies in the README ?

**Comment by AFaust** [comment]
I would primarily document the dependencies that we use, similar to how I do it in my [alfresco-simple-content-stores](https://github.com/Acosix/alfresco-simple-content-stores#dependencies) addon. Fat JARs introduce may even more potential runtime / classpath issues than Alfresco Simple Modules JARs already do on their own.

**Comment by yregaieg** [comment]
not if you do package rewrites using the maven shade plugin. But anyway I guess you have a valid point there ...

**Comment by AFaust** [comment]
With package rewrites, we would then again have to adapt our web script JS code, and it would no longer support the non-fat JAR deployment methods...
