### ISSUE TITLE
Reference error in SOLR tracking status: 'JSON' not available when run in Alfresco Enterprise 6.1.0.5

### ISSUE THREAD

**Issue by AFaust** [OrderOfTheBee/ootbee-support-tools#147]
## BUG
Running the OOTBee Support Tools 1.1.0.0 release on an Alfresco Content Services Repository using Enterprise Edition 6.1.0.5 with Share Services 6.1.0 installed, configured against Alfresco Search Services 1.3.0.6, the SOLR Tracking Status Admin Console Tool cannot be used. A reference error is reported, stating the the native JavaScript JSON class is not available / accessible in the server side JavaScript runtime in which the the web script runs.

### Expected behavior
The SOLR Tracking Status tool can be accessed and displays status information about the SOLR cores for the workspace and archive.

### Actual behavior
Loading the tool page fails with a server side web script / JavaScript error:

```text
Wrapped Exception (with status template): 08080044 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js': 08080043 ReferenceError: "JSON" is not defined. (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js#265)
```

The full stack trace in the log reads:

```text
2019-09-08 14:36:47,897 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [catalina-exec-4] Exception from executeScript: 08080002 Wrapped Exception (with status template): 08080044 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js': 08080043 ReferenceError: "JSON" is not defined. (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js#265)
org.springframework.extensions.webscripts.WebScriptException: 08080002 Wrapped Exception (with status template): 08080044 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js': 08080043 ReferenceError: "JSON" is not defined. (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js#265)
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1139)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:467)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
	at de.acosix.alfresco.utility.repo.web.scripts.TenantExtensibilityContainer.executeScript(TenantExtensibilityContainer.java:203)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at org.alfresco.repo.web.scripts.AlfrescoWebScriptServlet.service(AlfrescoWebScriptServlet.java:43)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.alfresco.web.app.servlet.ServletMetricsFilter.doFilter(ServletMetricsFilter.java:161)
	at org.alfresco.repo.web.filter.beans.BeanProxyFilter.doFilter(BeanProxyFilter.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.alfresco.web.app.servlet.ClearSecurityContextFilter.doFilter(ClearSecurityContextFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.alfresco.scripts.ScriptException: 08080044 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js': 08080043 ReferenceError: "JSON" is not defined. (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js#265)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:211)
	at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
	at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
	at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
	at de.acosix.alfresco.utility.repo.web.scripts.ExtensibleDeclarativeWebScript.executeScript(ExtensibleDeclarativeWebScript.java:61)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
	... 45 more
Caused by: org.alfresco.error.AlfrescoRuntimeException: 08080043 ReferenceError: "JSON" is not defined. (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js#265)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:533)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
	... 50 more
Caused by: org.mozilla.javascript.EcmaError: ReferenceError: "JSON" is not defined. (classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js#265)
	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.notFoundError(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.nameOrFunction(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.name(Unknown Source)
	at org.mozilla.javascript.gen.c2._c10(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js:265)
	at org.mozilla.javascript.gen.c2.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(Unknown Source)
	at org.mozilla.javascript.gen.c2._c0(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js:306)
	at org.mozilla.javascript.gen.c2.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
	at org.mozilla.javascript.gen.c2.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js)
	at org.mozilla.javascript.gen.c2.exec(classpath*:alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/solr-tracking.get.js)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
	... 51 more
```

The default Alfresco Enterprise Search Services tool page works fine, so there is no obscure error with talking to SOLR in general.

### Steps to reproduce the behavior

This issue has been reproduced by building a Repository WAR artifact using Maven, deployed manually on a Tomcat application server - no Docker images are involved. The following artifacts have been aggregated using the WAR build:

- Alfresco Enterprise 6.1.0.5
- Alfresco Share Services 6.1.0
- Alfresco Office Services 1.2.2
- OOTBee Support Tools 1.1.0.0
- JavaScript Console 0.6
- Customer-specific AMP

With this setup, the steps are:

- Start Alfresco Repository
- Start Alfresco Search Services
- Open Administration Console
- Access SOLR Tracking Status page

### Tell us about your environment

- Tomcat 8.5.38
- OpenJDK 11.0.2
- Windows 10

**Comment by AFaust** [comment]
This appears to be an issue with class file conflicts because the Mozilla Rhino appears to have been included separately via dependencies of the customer module. Specifically, the customer module includes an old version of Apache FOP, which has dependencies on various Batik (org.apache.xmlgraphics) libraries, including batik-js. This library bundles an older version of Mozilla Rhino without support for JSON (and other features). While apparently fine in a Docker-ised / Linux-based deployment, running the same WAR on Windows causes the failure due to a change in file system ordering and thus classloader order. So this is not a bug in OOTBee Support Tools, but the customer module.
